# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastemployment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personal',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='division', chained_model_field='division', null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.District'),
        ),
    ]
