# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180308_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bluetooth', models.BooleanField(default=False)),
                ('camera', models.BooleanField(default=False)),
                ('dual_lens_camera', models.BooleanField(default=False)),
                ('dual_sim', models.BooleanField(default=False)),
                ('expandable_memory', models.BooleanField(default=False)),
                ('fingerprint_sensor', models.BooleanField(default=False)),
                ('gps', models.BooleanField(default=False)),
                ('physical_keyboard', models.BooleanField(default=False)),
                ('motion_sensors', models.BooleanField(default=False)),
                ('three_g', models.BooleanField(default=False)),
                ('four_g', models.BooleanField(default=False)),
                ('gsm', models.BooleanField(default=False)),
                ('touch_screen', models.BooleanField(default=False)),
            ],
        ),
    ]
