# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mobilephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='codition',
            new_name='condition',
        ),
    ]
