# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_audiomp3'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.DateTimeField(blank=True, null=True)),
                ('registration_year', models.DateTimeField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=100, null=True)),
                ('body_type', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=255, null=True)),
                ('engine_capacity', models.FloatField(blank=True, null=True)),
                ('kilometer_run', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
