# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorbikeScooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.DateTimeField(blank=True, null=True)),
                ('engine_capacity', models.FloatField(blank=True, null=True)),
                ('kilometer_run', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
