# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_autoservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.IntegerField(blank=True, null=True)),
                ('bath', models.IntegerField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
