# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_type', models.CharField(blank=True, max_length=50, null=True)),
                ('land_size', models.FloatField(blank=True, null=True)),
                ('land_size_scale', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
