# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_healthlifestyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
