# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_childrenitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbook_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
