# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_farmanimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
