# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Type'),
        ),
    ]
