# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_catagory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='type_of',
        ),
    ]
