# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_remove_catagory_type_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='look_for_property_to_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catagory',
            name='look_for_something_to_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catagory',
            name='offer_property_for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catagory',
            name='post_job_vacancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catagory',
            name='sell_item_or_service',
            field=models.BooleanField(default=False),
        ),
    ]
