# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20180319_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentApartmentFlat',
            fields=[
                ('apartmentflat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.ApartmentFlat')),
                ('feature', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('home.apartmentflat',),
        ),
    ]
