# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_rentcommercialproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBangladesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('business_function', models.CharField(blank=True, max_length=100, null=True)),
                ('role_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('receive_applications_via', models.CharField(blank=True, max_length=100, null=True)),
                ('total_vacancy', models.IntegerField(blank=True, null=True)),
                ('application_deadline', models.DateField(auto_now_add=True)),
                ('company_employer', models.CharField(blank=True, max_length=100, null=True)),
                ('minimum_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('required_experience', models.FloatField(blank=True, null=True)),
                ('educational_specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('skill', models.CharField(blank=True, max_length=255, null=True)),
                ('maximum_age', models.IntegerField(blank=True, null=True)),
                ('gender_preference', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
