# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_jobbangladesh'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverseasJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('apply_via', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.CharField(blank=True, max_length=100, null=True)),
                ('application_deadline', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
