from django.contrib import admin

from . import models


admin.site.register(models.Catagory)
admin.site.register(models.SubCatagory)
admin.site.register(models.Product)
admin.site.register(models.MobilePhone)
admin.site.register(models.ComputerTablet)
admin.site.register(models.ComputerAccessories)
admin.site.register(models.TvAccessories)
admin.site.register(models.CameraCamcoder)
admin.site.register(models.AudioMP3)
admin.site.register(models.Car)
admin.site.register(models.MotorbikeScooter)
admin.site.register(models.BicycleThreeWheeler)
admin.site.register(models.TruckVanBus)
admin.site.register(models.AutoPartAccessory)
admin.site.register(models.AutoService)
admin.site.register(models.ApartmentFlat)
admin.site.register(models.House)
admin.site.register(models.PlotLand)
admin.site.register(models.Garage)
admin.site.register(models.CommercialProperty)
admin.site.register(models.BusinessTechnical)
admin.site.register(models.TravelVisa)
admin.site.register(models.Ticket)
admin.site.register(models.EventHospitality)
admin.site.register(models.DomesticPersonal)
admin.site.register(models.HealthLifestyle)
admin.site.register(models.Furniture)
admin.site.register(models.HomeAppliance)
admin.site.register(models.ElectricityACBathroomGarden)
admin.site.register(models.Cloth)
admin.site.register(models.ShoeFootware)
admin.site.register(models.HealthBeauty)
admin.site.register(models.MusicalInstrument)
admin.site.register(models.SportEquipment)
admin.site.register(models.HandicraftDecoration)
admin.site.register(models.MusicBookMovie)
admin.site.register(models.ChildrenItem)
