# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thana',
            name='division',
        ),
    ]
